executable lys-compiler
  main-is:             Main.hs
  other-modules:       Language.Lys.Parser
                     , Language.Lys.Parser.AST
                     , Language.Lys.Parser.Program
                     , Language.Lys.Parser.Declaration
                     , Language.Lys.Parser.Type
                     , Language.Lys.Parser.Process
                     , Language.Lys.Parser.Name
                     , Language.Lys.Parser.Lexer
                     , Language.Lys.Parser.Types
                     , Language.Lys.TypeChecking
                     , Language.Lys.TypeChecking.Program
                     , Language.Lys.TypeChecking.Declaration
                     , Language.Lys.TypeChecking.Inference
                     , Language.Lys.TypeChecking.Types
                     , Language.Lys.TypeChecking.Debug
                     , Language.Lys.Core
                     , Language.Lys.Desugar
                     , Language.Lys.Pretty
                     , Language.Lys.Pretty.AST
                     , Language.Lys.Pretty.Core
                     , Language.Lys.Pretty.Type
                     , Language.Lys.Pretty.Types
                     , Language.Lys.Pretty.Class
                     , Language.Lys.Types
                     , Language.Lys.Types.Env
                     , Language.Lys.Types.Context
                     , Language.Lys

  extensions:          LambdaCase
                     , BlockArguments

  build-depends:       base            >=4.5   && <5
                     , deriving-compat >=0.3.4 && <0.6
                     , recursion-schemes ==5.*
                     , recursion-schemes-ext >=1
                     , composition-prelude ==2.0.4.0
                     , megaparsec ==7.*
                     , parser-combinators ==1.*
                     , comonad >=4 && <6
                     , text ==1.2.*
                     , containers ==0.6.*
                     , multimap ==1.2.*
                     , mtl ==2.2.*
                     , free ==5.*
                     , lens ==4.*
                     , these ==0.8
                     , time ==1.8.*
                     , keys ==3.12.*
                     , ansi-wl-pprint ==0.6.*
  hs-source-dirs:      src
  default-language:    Haskell2010
